version: "3.5"

services:
  # Source: https://www.jenkins.io/doc/book/installing/docker/
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-data:/var/lib/docker
    privileged: true
    restart: unless-stopped
    command: --storage-driver=overlay2
    network_mode: "service:jenkins-blueocean"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
  
  # Jenkins controller
  jenkins-blueocean:
    container_name: jenkins-blueocean
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://localhost:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins
    restart: unless-stopped
    ports:
      - 127.0.0.1:2376:2376
      - 127.0.0.1:8080:8080
      - 127.0.0.1:50000:50000
    privileged: true

  sonarqube-init:
    image: bash
    privileged: true
    user: root
    volumes:
      - "/d/Mes Documents/swarm_game/cdci/sonarqube-init.sh:/mnt/init.sh"
    command: ["sh", "-e", "/mnt/init.sh"]
  
  # Source: https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.1-community
    depends_on:
      - sonarqube-init
      - sonarqube-db
    ports:
      - 127.0.0.1:9000:9000
    networks:
      - jenkins
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonarqube-db:
    container_name: sonarqube-db
    image: postgres
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    restart: unless-stopped
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
  jenkins-docker-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
