[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["chris-adam <adam.chris@live.be>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
